### ISSUE TITLE
some measures are floats

### ISSUE THREAD

**Issue by jlapenna** [vangorra/python_withings_api#14]
Getting devices...
Getting measures...
Getting activity...
Traceback (most recent call last):
  File "./scripts/integration_test.py", line 119, in <module>
    main()
  File "./scripts/integration_test.py", line 93, in main
    startdateymd=arrow.utcnow().shift(days=-21), enddateymd=arrow.utcnow()
  File "/home/jlapenna/code/python_withings_api/venv/lib/python3.6/site-packages/withings_api-2.1.2b1-py3.6.egg/withings_api/__init__.py", line 131, in measure_get_activity
  File "/home/jlapenna/code/python_withings_api/venv/lib/python3.6/site-packages/withings_api-2.1.2b1-py3.6.egg/withings_api/common.py", line 652, in new_measure_get_activity_response
  File "/home/jlapenna/code/python_withings_api/venv/lib/python3.6/site-packages/withings_api-2.1.2b1-py3.6.egg/withings_api/common.py", line 652, in <genexpr>
  File "/home/jlapenna/code/python_withings_api/venv/lib/python3.6/site-packages/withings_api-2.1.2b1-py3.6.egg/withings_api/common.py", line 636, in new_measure_get_activity_activity
  File "/home/jlapenna/code/python_withings_api/venv/lib/python3.6/site-packages/withings_api-2.1.2b1-py3.6.egg/withings_api/common.py", line 404, in int_or_raise
  File "/home/jlapenna/code/python_withings_api/venv/lib/python3.6/site-packages/withings_api-2.1.2b1-py3.6.egg/withings_api/common.py", line 369, in enforce_type
withings_api.common.UnexpectedTypeException: Expected of "296.34" to be "<class 'int'>" but was "<class 'float'>."

I didn't have a chance to check out which measure it was; will do in a follow-up comment.

**Comment by vangorra** [comment]
Fixed in commit 0d6c084f0686a758a9941b57a68d1328cde17ce9
