### ISSUE TITLE
Error Refreshing Token

### ISSUE THREAD

**Issue by jdubz666** [vangorra/python_withings_api#25]
Hi,

I'm trying to Manually Refresh the token. The Integration_test..py works until the token expires.  Then I am unable to refresh the token. Is there anything I am missing for this to work?

Thank you!

Below is my error...

Traceback (most recent call last):
  File "./scripts/integration_test.py", line 132, in <module>
    main()
  File "./scripts/integration_test.py", line 86, in main
    api.refresh_token()
  File "/usr/local/lib/python3.7/dist-packages/withings_api/__init__.py", line 415, in refresh_token
    token_dict = self._client.refresh_token(token_url=self._client.auto_refresh_url)
  File "/usr/local/lib/python3.7/dist-packages/requests_oauthlib/oauth2_session.py", line 309, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.7/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 389, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.

**Comment by jdubz666** [comment]
help?

**Comment by vangorra** [comment]
The error suggest you don't have any tokens set. Since the integration test is working, my best guess is you are not saving/loading the tokens between runs.

**Comment by jdubz666** [comment]
Thank you for the response. 

How would I save and load tokens?

**Comment by jdubz666** [comment]
I guess I have to use a database outside of the python script to store and load tokens...

Do you have examples of what to use?

**Comment by jdubz666** [comment]
How would I save and load tokens between runs?

**Comment by vangorra** [comment]
You can use a callback to get the latest credentials whenever they are updated. https://github.com/vangorra/python_withings_api/blob/master/withings_api/__init__.py#L371

You can use pickle to serialize and deserialize the named tuple.

**Comment by jdubz666** [comment]
Sorry I don’t quite understand. The code you referenced to is commented out.

Do you have sample code you could please show me for this save function?

**Comment by vangorra** [comment]
No. Using the pickle module will make it easy to serialize and serialize the credentials named tuple
