### ISSUE TITLE
Invalid State when following redirect URI

### ISSUE THREAD

**Issue by jdubz666** [vangorra/python_withings_api#84]
Hi,

When I run integration_test.py and paste the URL into my browser the web page shows "Invalid State"

Any ideas how I can fix this to get the credentials file?

Thanks,
Jack

**Comment by jdubz666** [comment]
When I paste the URL back into the prompt I receive this error.  The code I receive from the URL should work outside of integration_test.py because I was able to use it to make post requests with it.

Traceback (most recent call last):
  File "/home/jack/python_withings_api/scripts/integration_test.py", line 159, in <module>
    main()
  File "/home/jack/python_withings_api/scripts/integration_test.py", line 102, in main
    save_credentials(auth.get_credentials(auth_code))
  File "/usr/local/lib/python3.8/dist-packages/withings_api/__init__.py", line 419, in get_credentials
    response: Final = self._session.fetch_token(
  File "/usr/local/lib/python3.8/dist-packages/requests_oauthlib/oauth2_session.py", line 366, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/errors.py", line 406, in raise_from_error
    raise CustomOAuth2Error(error=error, **kwargs)
oauthlib.oauth2.rfc6749.errors.CustomOAuth2Error: (0)
